import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { BriefingContent, BriefingAlert, KpiSnapshot } from '@/types/briefing'

/**
 * GET /api/intelligence/briefing?date=YYYY-MM-DD&companyId=<id>
 *
 * Returns the morning briefing for a specific date and company
 * Includes critical alerts, KPI snapshot, and recommended actions
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const date = searchParams.get('date') || new Date().toISOString().split('T')[0]
    const companyId = searchParams.get('companyId')

    if (!companyId) {
      return NextResponse.json(
        { error: 'companyId is required' },
        { status: 400 }
      )
    }

    // Get user's news preferences
    const preferences = await db.query(
      'SELECT * FROM news_preferences WHERE company_id = $1 LIMIT 1',
      [companyId]
    )

    if (preferences.rowCount === 0) {
      return NextResponse.json(
        { error: 'No preferences found for this company' },
        { status: 404 }
      )
    }

    const prefs = preferences.rows[0]

    // Get news articles and impacts from the past 24 hours
    const alerts = await db.query(`
      SELECT
        a.id,
        a.headline,
        a.url,
        a.published_at,
        a.ai_summary,
        s.name as source,
        ni.impact_type,
        ni.impact_description,
        ni.probability,
        ni.urgency,
        ni.recommended_action,
        ni.related_kpis
      FROM news_articles a
      JOIN news_sources s ON a.source_id = s.id
      JOIN news_impacts ni ON a.id = ni.article_id
      WHERE
        ni.company_id = $1
        AND a.created_at >= NOW() - INTERVAL '24 hours'
        AND ni.urgency IN ($2, $3, $4)
      ORDER BY ni.urgency = 'immediate' DESC, a.published_at DESC
      LIMIT 20
    `, [companyId, prefs.min_urgency_threshold, 'this-week', 'immediate'])

    // Get current KPI snapshot (from intelligence hub)
    const kpiSnapshot = await getKpiSnapshot(companyId)

    // Get competitor intelligence updates
    const competitors = await db.query(`
      SELECT
        competitor_name,
        latest_funding_amount,
        latest_funding_date,
        growth_rate_pct,
        revenue_estimate
      FROM competitor_intelligence
      WHERE company_id = $1
      ORDER BY latest_funding_date DESC
      LIMIT 5
    `, [companyId])

    // Count critical vs regular alerts
    const criticalCount = alerts.rows.filter(a => a.urgency === 'immediate').length
    const regularCount = alerts.rows.filter(a => a.urgency !== 'immediate').length

    // Build briefing content
    const briefing: BriefingContent = {
      companyId,
      timestamp: new Date(),
      criticalAlerts: alerts.rows.map(row => ({
        articleId: row.id,
        headline: row.headline,
        source: row.source,
        publishedAt: row.published_at,
        impact: {
          id: '', // Generated by impact service
          articleId: row.id,
          companyId,
          impactType: row.impact_type,
          impactDescription: row.impact_description,
          probability: row.probability,
          urgency: row.urgency,
          relatedKpis: row.related_kpis || [],
          createdAt: new Date(),
        },
        aiSummary: row.ai_summary,
        urgency: row.urgency,
        recommendedAction: row.recommended_action,
        relatedDocuments: [], // Would fetch from data room
      })),
      kpiSnapshot,
      competitorIntelligence: competitors.rows.map(row => ({
        competitorName: row.competitor_name,
        recentNews: {
          headline: `Funding announcement: ${row.latest_funding_amount ? `$${row.latest_funding_amount}M` : 'amount undisclosed'}`,
          type: 'funding' as const,
          date: row.latest_funding_date,
          source: 'Crunchbase',
        },
        comparison: {
          growthRate: row.growth_rate_pct || 0,
          margin: 0, // Would calculate
          implication: `Growth rate ${row.growth_rate_pct || 0}% vs our 42%`,
          recommendation: 'Emphasize our superior growth and margins to investors',
        },
      })),
      recommendedActions: [
        {
          type: 'immediate',
          title: 'Review SEC delay impact',
          description: 'Update financial model and timeline projections for 45-day SEC review',
          impactArea: ['timeline', 'financial_model'],
          timeEstimate: '2 hours',
          relatedArticles: [],
          relatedMetrics: ['cash_runway', 'pace_score'],
          suggestedDocuments: ['Financial Model', 'Prospectus Draft'],
        },
      ],
      unreadArticleCount: alerts.rowCount,
    }

    return NextResponse.json(briefing)
  } catch (error) {
    console.error('Briefing fetch error:', error)
    return NextResponse.json(
      { error: 'Failed to fetch briefing' },
      { status: 500 }
    )
  }
}

/**
 * Helper: Fetch current KPI snapshot
 */
async function getKpiSnapshot(companyId: string): Promise<KpiSnapshot> {
  // In a real implementation, this would fetch from the analytics/dashboard tables
  // For now, returning mock data that would be updated by scheduled job

  return {
    paceScore: 73,
    paceTarget: 85,
    monthlyRevenue: 1040000,
    arr: 12400000,
    grossMarginPct: 76,
    cashRunwayMonths: 8.4,
    churnPct: 2.1,
    capTableClarity: 95,
    governanceScore: 78,
    prediction: {
      paceScoreTrendDays: 30,
      runwayDepletionDate: '2026-09-15',
      nextMilestoneDate: '2026-07-01',
    },
  }
}
