import { Task, Phase, Exchange, ListingType } from '@/types'

export interface ChecklistTask {
  phase: Phase
  category: string
  title: string
  description: string
  priority: 'critical' | 'high' | 'medium' | 'low'
  estimatedDays: number
  learnMoreUrl: string
  secCitation?: string
  sedarCitation?: string
  commonPitfalls: string[]
  examples: string[]
  applicableExchanges: Exchange[]
  applicableListingTypes: ListingType[]
  order: number
}

export const IPO_CHECKLIST: ChecklistTask[] = [
  // ─────────────────────── PHASE 1: PRE-PLANNING ───────────────────────
  {
    phase: 'pre_planning',
    category: 'Strategic Decision',
    title: 'Determine listing readiness & exchange suitability',
    description: 'Conduct an internal readiness assessment to determine if the company meets minimum listing standards for the target exchange. Evaluate financial history, governance, and operational maturity.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.tsx.com/listings/listing-with-us/listing-requirements',
    sedarCitation: 'TSX Company Manual s.309 — Minimum Listing Requirements',
    commonPitfalls: [
      'Underestimating time required — most companies take 2–4x longer than planned',
      'Not stress-testing the balance sheet before public scrutiny',
      'Choosing the wrong exchange for your sector and market cap',
    ],
    examples: [
      'A mining junior with $250K in assets qualifies for CSE but not TSX',
      'Tech companies with negative EBITDA may qualify under TSXV Technology Tier',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'pre_planning',
    category: 'Strategic Decision',
    title: 'Engage a go-public advisor / investment banker',
    description: 'Select and retain an experienced go-public advisor or investment banker who specializes in your target exchange and sector. This professional will quarterback the entire process.',
    priority: 'critical',
    estimatedDays: 7,
    learnMoreUrl: 'https://www.iiroc.ca/dealers-advisors/registration/registration-categories',
    commonPitfalls: [
      'Hiring an advisor without exchange-specific experience',
      'Not checking the advisor\'s track record on completed listings',
      'Skipping reference checks — a bad advisor delays everything by months',
    ],
    examples: [
      'Canaccord Genuity, Raymond James, National Bank for Canadian exchanges',
      'Goldman Sachs, Morgan Stanley, Jefferies for US exchanges',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 2,
  },
  {
    phase: 'pre_planning',
    category: 'Legal',
    title: 'Engage securities lawyers (issuer\'s counsel)',
    description: 'Retain a law firm with deep securities expertise in your target jurisdiction. They will draft or review all disclosure documents, manage regulatory communications, and ensure compliance.',
    priority: 'critical',
    estimatedDays: 7,
    learnMoreUrl: 'https://www.securities-administrators.ca',
    secCitation: 'SEC Rule 14a-3 — Requirement for Legal Opinion',
    commonPitfalls: [
      'Using a general practice firm without securities law depth',
      'Not engaging US securities counsel when doing a dual-listing',
      'Underbudgeting legal fees (typically $200K–$800K+ for a full IPO)',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 3,
  },
  {
    phase: 'pre_planning',
    category: 'Financial',
    title: 'Engage PCAOB/CPAB registered auditors',
    description: 'Retain an audit firm registered with PCAOB (US) or CPAB (Canada) to perform the required financial statement audits. Most exchanges require 2–3 years of audited financials.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://pcaobus.org/Registration/Firms',
    secCitation: 'SEC S-1 Registration — Regulation S-X Rule 2-02',
    sedarCitation: 'NI 41-101 s.4.2 — Audit Requirements',
    commonPitfalls: [
      'Using a non-registered audit firm — regulators will reject filings',
      'Not having 2–3 years of comparative financial statements ready',
      'Accounting policy choices that don\'t survive public scrutiny (revenue recognition)',
    ],
    examples: [
      'Big 4: Deloitte, PwC, EY, KPMG',
      'Mid-tier: MNP, BDO, Grant Thornton for smaller issuers',
      'Visit auditus.ai for pre-audit preparation services',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 4,
  },
  {
    phase: 'pre_planning',
    category: 'Governance',
    title: 'Conduct board composition assessment',
    description: 'Evaluate current board composition against listing requirements. Most exchanges require a majority of independent directors and specific audit committee members.',
    priority: 'high',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.tsx.com/resource/en/64',
    sedarCitation: 'NI 52-110 — Audit Committee Requirements; NI 58-101 — Disclosure of Corporate Governance',
    secCitation: 'NASDAQ Rule 5605 — Board Independence Requirements',
    commonPitfalls: [
      'Not identifying independent director candidates early enough',
      'Forgetting that board members need to be approved by exchanges (PIFs required)',
      'Having too many related-party directors on the audit committee',
    ],
    examples: [
      'TSXV requires min. 2 independent directors; TSX requires majority independent',
      'NASDAQ requires 3 independent audit committee members with financial literacy',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 5,
  },
  {
    phase: 'pre_planning',
    category: 'Strategic Decision',
    title: 'Determine capital raise structure & offering size',
    description: 'Define the offering structure: size of raise, use of proceeds, price range, lockup agreements, and underwriter allocation. This shapes the entire prospectus and marketing strategy.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.investopedia.com/terms/i/ipo.asp',
    commonPitfalls: [
      'Over-raising and diluting existing shareholders excessively',
      'Under-raising and being undercapitalized post-listing',
      'Not stress-testing the valuation with comparable transactions',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac'],
    order: 6,
  },

  // ──────────────── PHASE 2: CORPORATE RESTRUCTURING ────────────────
  {
    phase: 'corporate_restructuring',
    category: 'Legal',
    title: 'Review and update articles of incorporation',
    description: 'Review and amend corporate articles to meet exchange requirements: authorized share structure, classes of shares, voting rights, and restrictions on transfer.',
    priority: 'critical',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/corporations/incorporate-business.html',
    commonPitfalls: [
      'Not removing private company share transfer restrictions before filing',
      'Insufficient authorized share capital for the offering plus stock options',
      'Dual-class share structures creating governance concerns for investors',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'corporate_restructuring',
    category: 'Governance',
    title: 'Adopt corporate governance policies',
    description: 'Implement required governance policies: Audit Committee Charter, Compensation Committee Charter, Code of Conduct, Whistleblower Policy, Disclosure Policy, Insider Trading Policy.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.icd.ca/Governance-Resources/Governance-Tools',
    sedarCitation: 'NI 58-101 — Disclosure of Corporate Governance Practices',
    secCitation: 'SEC Item 407 — Corporate Governance',
    commonPitfalls: [
      'Adopting boilerplate policies without tailoring to your business',
      'Failing to actually implement policies (regulators check for evidence)',
      'Missing the Clawback Policy requirement (now mandatory for NASDAQ/NYSE)',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 2,
  },
  {
    phase: 'corporate_restructuring',
    category: 'Governance',
    title: 'Establish audit committee with financial experts',
    description: 'Form a fully independent audit committee with at least one financial expert per SEC/exchange rules. Adopt the Audit Committee Charter and ensure members understand their legal obligations.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://pcaobus.org/EconomicAndRiskAnalysis/pir/Documents/Audit_Committee_Resource_Guide.pdf',
    sedarCitation: 'NI 52-110 — Audit Committee',
    secCitation: 'SOX Section 301 — Audit Committee Requirements',
    commonPitfalls: [
      'Appointing directors without true financial literacy',
      'Audit committee members who have financial relationships with the company',
      'Chair without prior public company board experience',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 3,
  },
  {
    phase: 'corporate_restructuring',
    category: 'Legal',
    title: 'Complete all PIF (Personal Information Form) filings',
    description: 'All directors, officers, promoters, and key shareholders must complete Personal Information Forms (PIFs) for exchange approval. Background checks are conducted on all PIFs.',
    priority: 'critical',
    estimatedDays: 30,
    learnMoreUrl: 'https://www.tsx.com/listings/listing-with-us/listing-requirements/directors-officers-and-promoters',
    sedarCitation: 'TSX Company Manual Appendix A — Personal Information Form',
    commonPitfalls: [
      'PIF rejections due to undisclosed past regulatory issues — be transparent',
      'Missing PIFs for indirect beneficial owners with >10% interest',
      'Delays because PIFs take 4–8 weeks to process at exchanges',
    ],
    examples: [
      'TSXV Form 2B — Personal Information Form',
      'TSX Appendix A — Personal Information Form',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac'],
    order: 4,
  },
  {
    phase: 'corporate_restructuring',
    category: 'Legal',
    title: 'Establish employee stock option / equity incentive plan',
    description: 'Draft and approve a Stock Option Plan or Equity Incentive Plan meeting exchange rules. This must be approved by shareholders and comply with "rolling" or "fixed" plan requirements.',
    priority: 'high',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.tsx.com/listings/listing-with-us/rules-and-policies/company-manual',
    sedarCitation: 'TSX Company Manual s.613 — Security-Based Compensation',
    commonPitfalls: [
      'Option plan exceeding 10% of issued shares without shareholder approval',
      'Not complying with "fixed" plan re-approval every 3 years on TSX',
      'Insider grants in blackout periods violating insider trading policies',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 5,
  },
  {
    phase: 'corporate_restructuring',
    category: 'Legal',
    title: 'Complete pre-IPO financing and cleanup (convertibles, warrants)',
    description: 'Resolve all pre-IPO financing instruments: convert convertible notes, exercise or cancel warrants, clean up cap table, and ensure all agreements are assignable post-listing.',
    priority: 'high',
    estimatedDays: 30,
    learnMoreUrl: 'https://www.investopedia.com/articles/investing/060915/understanding-cap-tables.asp',
    commonPitfalls: [
      'Convertible notes converting at IPO price, creating unexpected dilution',
      'Anti-dilution ratchets surprising new public investors',
      'Material agreements with change-of-control provisions triggered by listing',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac'],
    order: 6,
  },
  {
    phase: 'corporate_restructuring',
    category: 'Financial',
    title: 'Implement public company financial reporting systems',
    description: 'Upgrade accounting systems, internal controls, and financial close processes to meet public company standards. Evaluate ERP readiness and reporting timelines.',
    priority: 'high',
    estimatedDays: 45,
    learnMoreUrl: 'https://www.cpacanada.ca/en/business-and-accounting-resources/financial-and-non-financial-reporting',
    secCitation: 'SOX Section 302 & 404 — Internal Controls',
    sedarCitation: 'NI 52-109 — CEO/CFO Certification',
    commonPitfalls: [
      'Underestimating the time to implement SOX 404 controls',
      'Not having a quarterly close process ready within 45 days of quarter end',
      'Inadequate documentation of internal controls prior to first audit',
    ],
    examples: [
      'Typical public company financial close: 25–45 days after quarter end',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 7,
  },

  // ───────────────────── PHASE 3: FINANCIAL AUDIT ─────────────────────
  {
    phase: 'financial_audit',
    category: 'Financial',
    title: 'Complete 2–3 years audited financial statements',
    description: 'Auditor performs full audit of 2–3 fiscal years of financial statements under applicable GAAP (IFRS or US GAAP). Statements must be in the correct format and include all required notes.',
    priority: 'critical',
    estimatedDays: 90,
    learnMoreUrl: 'https://www.ifrs.org',
    secCitation: 'Regulation S-X — Form and Content of Financial Statements',
    sedarCitation: 'NI 41-101 Form 41-101F1 — Prospectus Financial Statement Requirements',
    commonPitfalls: [
      'Revenue recognition policies (IFRS 15 / ASC 606) not properly applied',
      'Related party transactions not disclosed or improperly valued',
      'Going concern issues requiring additional disclosure',
      'Restatements discovered mid-prospectus — catastrophic delay',
    ],
    examples: [
      'For NASDAQ/NYSE: US GAAP or IFRS accepted',
      'For TSX/TSXV/CSE: IFRS required for Canadian issuers',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'financial_audit',
    category: 'Financial',
    title: 'Obtain auditor comfort letters',
    description: 'Secure auditor comfort letters for inclusion in the prospectus. These address financial data accuracy and are required by underwriters.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://pcaobus.org',
    secCitation: 'AU-C Section 920 — Letters for Underwriters (SAS 72)',
    commonPitfalls: [
      'Requesting comfort letters too late — they require 3–4 weeks minimum',
      'Interim financial data in the prospectus not covered by a comfort letter',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 2,
  },
  {
    phase: 'financial_audit',
    category: 'Financial',
    title: 'Pre-audit preparation with auditus.ai',
    description: 'Leverage auditus.ai to complete pre-audit due diligence, organize financial documentation, identify gaps, and prepare management representations before the formal audit begins. This can reduce audit fees by 20–40%.',
    priority: 'high',
    estimatedDays: 30,
    learnMoreUrl: 'https://auditus.ai',
    commonPitfalls: [
      'Entering the formal audit unprepared — dramatically increases fees and time',
      'Not reconciling all intercompany balances before audit starts',
      'Missing support for significant accounting estimates',
    ],
    examples: [
      'auditus.ai provides automated ledger analysis, gap identification, and audit-ready package preparation',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 3,
  },
  {
    phase: 'financial_audit',
    category: 'Financial',
    title: 'Complete MD&A (Management Discussion & Analysis)',
    description: 'Draft the Management Discussion and Analysis for each audited period. MD&A must explain financial results, liquidity, capital resources, and known trends in plain language.',
    priority: 'critical',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.sec.gov/rules/interp/33-8350.htm',
    secCitation: 'SEC Item 303 of Regulation S-K — MD&A Requirements',
    sedarCitation: 'NI 51-102 Form 51-102F1 — Management\'s Discussion and Analysis',
    commonPitfalls: [
      'Boilerplate language rejected by regulators — must be company-specific',
      'Not explaining key metrics and KPIs that management actually uses',
      'Inconsistency between MD&A and financial statements',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 4,
  },
  {
    phase: 'financial_audit',
    category: 'Financial',
    title: 'Complete working capital analysis and projections',
    description: 'Prepare detailed working capital analysis demonstrating the company has or will raise sufficient capital for 12 months post-listing. This is a key regulatory requirement.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.tsx.com/listings/listing-with-us/listing-requirements',
    commonPitfalls: [
      'Working capital deficiency at time of listing requires extensive disclosure',
      'Not stress-testing projections with downside scenarios',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 5,
  },

  // ─────────────────── PHASE 4: LEGAL DOCUMENTATION ───────────────────
  {
    phase: 'legal_documentation',
    category: 'Legal',
    title: 'Draft preliminary prospectus (red herring)',
    description: 'Prepare the preliminary prospectus (also called "red herring"). This is the primary disclosure document containing all material information about the company, the offering, and associated risks.',
    priority: 'critical',
    estimatedDays: 60,
    learnMoreUrl: 'https://www.securities-administrators.ca/uploadedFiles/General/pdfs/41-101F1_E_Final.pdf',
    secCitation: 'SEC Form S-1 / Form F-1 — Registration Statement',
    sedarCitation: 'NI 41-101 Form 41-101F1 — Prospectus',
    commonPitfalls: [
      'Risk factors that are generic rather than issuer-specific',
      'Incomplete or inaccurate description of the business',
      'Missing or inadequate related party transaction disclosure',
      'Use of proceeds not sufficiently detailed',
    ],
    examples: [
      'Typical length: 200–400 pages for a full prospectus',
      'Multiple rounds of SEC/securities commission comments expected',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'legal_documentation',
    category: 'Legal',
    title: 'Draft underwriting agreement',
    description: 'Negotiate and finalize the underwriting agreement with the lead underwriter, covering pricing, overallotment option (Green Shoe), representations & warranties, and indemnification.',
    priority: 'critical',
    estimatedDays: 30,
    learnMoreUrl: 'https://www.investopedia.com/terms/u/underwriting-agreement.asp',
    secCitation: 'SEC Item 601(b)(1) — Material Contracts',
    commonPitfalls: [
      'Overallotment options that are too large, diluting shareholders excessively',
      'Signing underwriting agreement before receiving exchange conditional approval',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo'],
    order: 2,
  },
  {
    phase: 'legal_documentation',
    category: 'Legal',
    title: 'Execute lock-up agreements with insiders',
    description: 'Obtain signed lock-up agreements from all insiders, executives, and major shareholders restricting sale of shares for 6–18 months post-listing.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.investopedia.com/terms/l/lockup-period.asp',
    secCitation: 'FINRA Rule 5110 — Lock-Up Restrictions',
    sedarCitation: 'TSX Company Manual s.602 — Escrow and Vendor Consideration',
    commonPitfalls: [
      'Escrow requirements differ by exchange — CSE less stringent than TSX',
      'Early release clauses that allow insiders to sell shortly after listing',
      'Not getting lock-ups from all holders of more than 5% of shares',
    ],
    examples: [
      'TSXV seed shares subject to escrow: 36-month escrow with 10%/6mo release',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 3,
  },
  {
    phase: 'legal_documentation',
    category: 'Legal',
    title: 'Complete all material contracts review and exhibit list',
    description: 'Identify, review, and organize all material contracts for prospectus disclosure and regulatory exhibits. This includes customer agreements, IP licenses, partnerships, and debt instruments.',
    priority: 'high',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.sec.gov/rules/final/33-8959.pdf',
    secCitation: 'SEC Item 601 of Regulation S-K — Exhibit Requirements',
    commonPitfalls: [
      'Failing to disclose material contracts that are later discovered',
      'Redacting too much from contracts — regulators push back',
      'Change-of-control clauses requiring third-party consents',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 4,
  },
  {
    phase: 'legal_documentation',
    category: 'Legal',
    title: 'Prepare transfer agent agreement and CUSIP/ISIN',
    description: 'Engage a registered transfer agent, execute the transfer agent agreement, and obtain CUSIP (US) or CUSIP/ISIN (Canada) numbers for your securities.',
    priority: 'critical',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.iiroc.ca',
    sedarCitation: 'CDS — Canadian Depository for Securities requirements',
    commonPitfalls: [
      'Not engaging transfer agent early enough — CUSIP/ISIN takes 3+ weeks',
      'Transfer agent not registered with the exchange\'s clearing system',
    ],
    examples: [
      'Canadian: Computershare, TSX Trust, Odyssey Trust',
      'US: Continental Stock Transfer, Computershare, American Stock Transfer',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 5,
  },

  // ─────────────────── PHASE 5: REGULATORY FILING ───────────────────
  {
    phase: 'regulatory_filing',
    category: 'Filing',
    title: 'File preliminary prospectus on SEDAR+/EDGAR',
    description: 'Submit the preliminary prospectus (receipt application) to the applicable securities commissions through SEDAR+ (Canada) or EDGAR (US). This initiates the regulatory review period.',
    priority: 'critical',
    estimatedDays: 7,
    learnMoreUrl: 'https://www.sedarplus.ca',
    sedarCitation: 'NI 41-101 s.2.1 — Preliminary Prospectus Filing',
    secCitation: 'SEC Regulation C — Requirements for Registration Statements',
    commonPitfalls: [
      'EDGAR system requirements for HTML/XBRL formatting — get technical help',
      'Incorrect filing fees leading to delayed acceptance',
      'Not coordinating multi-jurisdictional filing for all provinces/states',
    ],
    examples: [
      'SEDAR+ passcodes required for all filers — register 4+ weeks in advance',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'regulatory_filing',
    category: 'Filing',
    title: 'Respond to securities commission comment letters',
    description: 'Receive, review, and respond to deficiency letters from securities regulators (OSC, SEC, BCSC, etc.). Typically 2–4 rounds of comments, each requiring comprehensive written responses.',
    priority: 'critical',
    estimatedDays: 60,
    learnMoreUrl: 'https://www.sec.gov/cgi-bin/browse-edgar',
    secCitation: 'SEC Division of Corporation Finance — Comment Letter Process',
    commonPitfalls: [
      'Dismissive responses to regulator comments — they will push back harder',
      'Taking too long to respond — receipt lapses after certain period',
      'Not fully resolving comments on the first response, causing more rounds',
    ],
    examples: [
      'OSC review typically takes 10 business days per round',
      'SEC review takes 30 days for initial review, 10 days for subsequent',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 2,
  },
  {
    phase: 'regulatory_filing',
    category: 'Filing',
    title: 'Submit listing application to target exchange',
    description: 'File the formal listing application with all required schedules, supporting documents, and application fees. This is concurrent with or slightly before the final prospectus.',
    priority: 'critical',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.tsx.com/listings/listing-with-us',
    sedarCitation: 'TSX Company Manual Part III — Original Listing Requirements',
    commonPitfalls: [
      'Submitting incomplete listing application — rejected outright',
      'Not meeting minimum shareholder spread requirements',
      'Exchange listing fees underbudgeted (can be $10K–$200K+)',
    ],
    examples: [
      'TSXV listing application fee: $5,000–$40,000 depending on tier',
      'NASDAQ listing fee: $55,000–$155,000 depending on security type',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac'],
    order: 3,
  },
  {
    phase: 'regulatory_filing',
    category: 'Filing',
    title: 'Receive conditional listing approval from exchange',
    description: 'Exchange issues conditional approval letter listing all conditions that must be satisfied before the final listing date. Track and complete each condition.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.tsx.com',
    commonPitfalls: [
      'Not satisfying all conditions before the conditional approval expiry',
      'Missing the shareholder spread condition at the close of the IPO',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 4,
  },
  {
    phase: 'regulatory_filing',
    category: 'Filing',
    title: 'File final prospectus and obtain final receipt',
    description: 'After satisfying all regulator comments, file the final prospectus and receive a final receipt from all applicable securities commissions. This is the legal authorization to sell securities.',
    priority: 'critical',
    estimatedDays: 7,
    learnMoreUrl: 'https://www.sedarplus.ca',
    sedarCitation: 'NI 41-101 s.3.3 — Receipt for Final Prospectus',
    commonPitfalls: [
      'Pricing amendments after final receipt require 2-day marketing period',
      'Not having all selling group dealers signed up before final receipt',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 5,
  },

  // ─────────────────── PHASE 6: MARKETING & ROADSHOW ──────────────────
  {
    phase: 'marketing_roadshow',
    category: 'Marketing',
    title: 'Develop investor relations strategy & IR website',
    description: 'Create a public investor relations website meeting regulatory requirements. Build the corporate narrative, key messaging, and investor presentation.',
    priority: 'critical',
    estimatedDays: 21,
    learnMoreUrl: 'https://www.niri.org',
    secCitation: 'SEC Regulation FD — Fair Disclosure Requirements',
    sedarCitation: 'NI 51-102 — Continuous Disclosure Obligations',
    commonPitfalls: [
      'IR website not meeting NI 51-102 or SEC EDGAR requirements',
      'Selective disclosure violating Reg FD before and after listing',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'marketing_roadshow',
    category: 'Marketing',
    title: 'Conduct investor roadshow / book-building',
    description: 'Lead management and underwriters conduct roadshow presentations to institutional and retail investors to gauge demand and build the book. PATHFINDER meetings occur during preliminary prospectus period.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.investopedia.com/terms/r/roadshow.asp',
    commonPitfalls: [
      'Failing to answer tough investor questions — practice extensively',
      'Overpromising financial projections that can\'t be defended',
      'Management team not presenting with confidence and credibility',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo'],
    order: 2,
  },
  {
    phase: 'marketing_roadshow',
    category: 'Marketing',
    title: 'Issue press releases and investor presentations',
    description: 'Prepare and issue required press releases announcing the IPO and company milestones. Ensure all communications comply with securities laws (no selective disclosure).',
    priority: 'high',
    estimatedDays: 7,
    learnMoreUrl: 'https://www.sec.gov/rules/final/33-7856.htm',
    commonPitfalls: [
      'Premature publicity before registration effectiveness (gun-jumping)',
      'Forward-looking statements without adequate cautionary language',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'regulation_a'],
    order: 3,
  },

  // ──────────────────── PHASE 7: LISTING APPLICATION ──────────────────
  {
    phase: 'listing_application',
    category: 'Listing',
    title: 'Confirm final IPO pricing and share allocation',
    description: 'Price the offering based on book-building results. Finalize allocation between institutional and retail investors. Execute pricing amendment if required.',
    priority: 'critical',
    estimatedDays: 3,
    learnMoreUrl: 'https://www.investopedia.com/terms/b/bookbuilding.asp',
    commonPitfalls: [
      'Leaving too much money on the table with underpricing',
      'Overpricing causing immediate post-IPO stock decline',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo'],
    order: 1,
  },
  {
    phase: 'listing_application',
    category: 'Listing',
    title: 'Complete closing and settlement (T+2)',
    description: 'Complete the IPO closing: wire funds, issue shares to CDS/DTC, deliver legal opinions, and confirm settlement. Standard settlement is T+2.',
    priority: 'critical',
    estimatedDays: 3,
    learnMoreUrl: 'https://www.dtcc.com',
    commonPitfalls: [
      'Closing mechanics with CDS/DTC require advance booking',
      'Legal opinions not ready at closing — schedule counsel well in advance',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 2,
  },
  {
    phase: 'listing_application',
    category: 'Listing',
    title: 'Trading commencement — first day on exchange',
    description: 'Trading begins. Market maker provides liquidity. IR team monitors market activity and investor inquiries. Stabilization may be exercised if share price falls below IPO price.',
    priority: 'critical',
    estimatedDays: 1,
    learnMoreUrl: 'https://www.investopedia.com/terms/m/marketmaker.asp',
    commonPitfalls: [
      'No market maker engagement — thin trading and high bid/ask spreads',
      'Management not prepared for public company disclosure obligations starting Day 1',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 3,
  },

  // ──────────────────── PHASE 8: POST-LISTING COMPLIANCE ────────────────
  {
    phase: 'post_listing',
    category: 'Compliance',
    title: 'Establish continuous disclosure calendar',
    description: 'Implement a continuous disclosure compliance calendar including: quarterly financial statements, annual financial statements, annual information form (AIF), annual report, material change reports.',
    priority: 'critical',
    estimatedDays: 14,
    learnMoreUrl: 'https://www.osc.ca',
    sedarCitation: 'NI 51-102 — Continuous Disclosure Obligations',
    secCitation: 'SEC Exchange Act Sections 13 and 15(d) — Reporting Requirements',
    commonPitfalls: [
      'Missing filing deadlines — regulatory sanctions and potential delisting',
      'Not having public company IR and legal resources ready from Day 1',
    ],
    examples: [
      'Accelerated filer: Q1/Q2/Q3 within 45 days, Annual within 60 days',
      'Non-accelerated filer: Quarterly within 60 days, Annual within 90 days',
    ],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing', 'spac', 'regulation_a'],
    order: 1,
  },
  {
    phase: 'post_listing',
    category: 'Compliance',
    title: 'First quarterly earnings report preparation',
    description: 'Prepare the first post-listing quarterly earnings release, including financial statements, MD&A, earnings press release, and conference call materials.',
    priority: 'critical',
    estimatedDays: 30,
    learnMoreUrl: 'https://www.niri.org/niri/learning/learning-guide/earnings-guidance',
    commonPitfalls: [
      'Earnings calls without adequate preparation — damaging to stock price',
      'Guidance given in earnings call without understanding legal implications',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 2,
  },
  {
    phase: 'post_listing',
    category: 'Governance',
    title: 'Conduct first annual general meeting (AGM)',
    description: 'Plan and hold the first annual general meeting, including management information circular, proxy solicitation, director election, auditor appointment, and stock option plan ratification.',
    priority: 'high',
    estimatedDays: 60,
    learnMoreUrl: 'https://www.tsx.com/listings/maintaining-your-listing',
    sedarCitation: 'NI 54-101 — Proxy Solicitation; NI 51-102 — AGM Requirements',
    commonPitfalls: [
      'Not mailing the management information circular 21–60 days before AGM',
      'Missing TSX/NASDAQ quorum requirements',
    ],
    examples: [],
    applicableExchanges: ['tsx', 'tsxv', 'cse', 'nasdaq', 'nyse', 'otc', 'cboe'],
    applicableListingTypes: ['ipo', 'rto', 'direct_listing'],
    order: 3,
  },
]

export function getChecklistForListing(
  exchange: Exchange,
  listingType: ListingType
): ChecklistTask[] {
  return IPO_CHECKLIST.filter(
    task =>
      task.applicableExchanges.includes(exchange) &&
      task.applicableListingTypes.includes(listingType)
  ).sort((a, b) => {
    const phaseOrder = ['pre_planning', 'corporate_restructuring', 'financial_audit', 'legal_documentation', 'regulatory_filing', 'marketing_roadshow', 'listing_application', 'post_listing']
    const aPhase = phaseOrder.indexOf(a.phase)
    const bPhase = phaseOrder.indexOf(b.phase)
    if (aPhase !== bPhase) return aPhase - bPhase
    return a.order - b.order
  })
}
