/**
 * Prospectus Templates by Exchange
 * Defines section requirements, typical word counts, required subsections, and compliance rules
 * for different exchanges (NASDAQ S-1, NYSE, TSX 2A, TSXV, CSE, OTC, JSE)
 */

export interface ProspectusSection {
  sectionId: string;
  sectionNumber: string;
  sectionName: string;
  sectionDescription: string;
  required: boolean;
  typicalWordCount: number;
  minWordCount?: number;
  maxWordCount?: number;
  requiredSubsections: string[];
  mustInclude: string[]; // Required topics/disclosures
  mustNotInclude?: string[]; // Prohibited content
  complianceCategory: 'disclosure' | 'risk' | 'financial' | 'governance' | 'offering' | 'legal';
  priority: 'critical' | 'high' | 'medium' | 'low';
  dataSourceTypes: string[]; // Which document types feed this section
  aiGenerationGuidance?: string;
}

export interface ProspectusTemplate {
  exchangeId: string;
  exchangeName: string;
  formType: string; // S-1, 10, 2A, Reg A, etc.
  totalSections: number;
  typicalTotalWordCount: number;
  sections: ProspectusSection[];
  complianceFramework: string; // SEC Reg S-K, Canadian, Japanese FMSA, etc.
  estimatedCompletionDays: number;
  requiresProfessionalReview: boolean;
  requiresAuditorSignoff: boolean;
  requiresLawyerSignoff: boolean;
  version: string; // Template version for tracking
}

// ============================================================
// NASDAQ S-1 Template (US IPO - Growth/Established Companies)
// ============================================================
export const NASDAQ_S1: ProspectusTemplate = {
  exchangeId: 'NASDAQ',
  version: '1.0',
  exchangeName: 'NASDAQ',
  formType: 'S-1',
  totalSections: 12,
  typicalTotalWordCount: 45000,
  complianceFramework: 'SEC Regulation S-K',
  estimatedCompletionDays: 45,
  requiresProfessionalReview: true,
  requiresAuditorSignoff: true,
  requiresLawyerSignoff: true,
  sections: [
    {
      sectionId: 'NASDAQ-S1-01',
      sectionNumber: '1',
      sectionName: 'Summary',
      sectionDescription: 'Executive summary of business, growth strategy, key metrics, and investment highlights',
      required: true,
      typicalWordCount: 3500,
      minWordCount: 2500,
      maxWordCount: 5000,
      requiredSubsections: ['Company Overview', 'Our Opportunity', 'Our Strategy', 'Key Metrics', 'Recent Developments'],
      mustInclude: ['Revenue growth trajectory', 'Market opportunity', 'Competitive advantages', 'Management experience', 'Use of proceeds'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'FINANCIAL_STATEMENTS', 'MARKET_RESEARCH'],
      aiGenerationGuidance: 'Generate compelling narrative emphasizing growth potential and market traction. Highlight unique value propositions and competitive differentiation.',
    },
    {
      sectionId: 'NASDAQ-S1-02',
      sectionNumber: '2',
      sectionName: 'Risk Factors',
      sectionDescription: 'Comprehensive discussion of risks to business, industry, operations, and investment',
      required: true,
      typicalWordCount: 5000,
      minWordCount: 3000,
      maxWordCount: 8000,
      requiredSubsections: ['Business Risks', 'Industry Risks', 'Regulatory Risks', 'Financial Risks', 'Liquidity Risks'],
      mustInclude: ['Material adverse changes', 'Competition', 'Dependency risks', 'Technology/IP risks', 'Market risks', 'Regulatory/legal risks'],
      mustNotInclude: ['Mitigating factors should be in Risk Mitigation section, not here'],
      complianceCategory: 'risk',
      priority: 'critical',
      dataSourceTypes: ['LEGAL_OPINIONS', 'MARKET_RESEARCH', 'BUSINESS_PLAN'],
      aiGenerationGuidance: 'Be thorough and honest about risks. Use specific examples. Organize by category. Quantify impact where possible.',
    },
    {
      sectionId: 'NASDAQ-S1-03',
      sectionNumber: '3',
      sectionName: 'Use of Proceeds',
      sectionDescription: 'Detailed allocation of IPO proceeds across capital expenditure, working capital, debt repayment, and acquisitions',
      required: true,
      typicalWordCount: 2000,
      minWordCount: 1500,
      maxWordCount: 3000,
      requiredSubsections: ['Primary Use', 'Secondary Use', 'Timing of Use', 'Alternatives'],
      mustInclude: ['Total IPO proceeds', 'Percentage allocation', 'Timeline for deployment', 'Contingency plans'],
      complianceCategory: 'offering',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'BUSINESS_PLAN'],
      aiGenerationGuidance: 'Be specific with percentages and timelines. Show how proceeds support growth strategy from Summary section.',
    },
    {
      sectionId: 'NASDAQ-S1-04',
      sectionNumber: '4',
      sectionName: 'Capitalization',
      sectionDescription: 'Detailed capitalization table with all outstanding equity, warrants, options, and convertible securities',
      required: true,
      typicalWordCount: 3000,
      minWordCount: 2000,
      maxWordCount: 5000,
      requiredSubsections: ['Current Capitalization', 'Post-IPO Capitalization', 'Option Pool', 'Warrant Holders', 'Convertible Securities'],
      mustInclude: ['Common stock outstanding', 'Preferred stock details', 'Option plans', 'Major shareholder list', 'Dilution analysis'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['CAP_TABLE', 'ARTICLES_OF_INCORPORATION', 'BOARD_MINUTES'],
      aiGenerationGuidance: 'Extract directly from cap table. Show fully diluted basis. Include post-IPO scenarios with different offer sizes.',
    },
    {
      sectionId: 'NASDAQ-S1-05',
      sectionNumber: '5',
      sectionName: 'Selected Financial Data',
      sectionDescription: 'Five-year historical financial performance with key metrics and ratios',
      required: true,
      typicalWordCount: 2500,
      minWordCount: 2000,
      maxWordCount: 4000,
      requiredSubsections: ['Five-Year Summary', 'Key Metrics', 'Financial Ratios', 'Non-GAAP Metrics'],
      mustInclude: ['Revenue', 'Gross profit', 'Operating income', 'Net income', 'Adjusted EBITDA', 'Key operating metrics'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
      aiGenerationGuidance: 'Pull directly from audited financials. Calculate year-over-year growth rates. Highlight key inflection points.',
    },
    {
      sectionId: 'NASDAQ-S1-06',
      sectionNumber: '6',
      sectionName: 'Management\'s Discussion and Analysis (MD&A)',
      sectionDescription: 'Detailed management analysis of results of operations, liquidity, capital resources, and financial condition',
      required: true,
      typicalWordCount: 8000,
      minWordCount: 6000,
      maxWordCount: 12000,
      requiredSubsections: ['Overview', 'Results of Operations', 'Liquidity and Capital Resources', 'Critical Accounting Policies', 'Forward-Looking Statements'],
      mustInclude: ['YoY comparisons', 'Margin analysis', 'Cash flow trends', 'Key drivers of performance', 'Future outlook'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'BOARD_MINUTES', 'BUSINESS_PLAN'],
      aiGenerationGuidance: 'Write in management voice. Explain the "why" behind numbers. Connect to strategy and outlook.',
    },
    {
      sectionId: 'NASDAQ-S1-07',
      sectionNumber: '7',
      sectionName: 'Business',
      sectionDescription: 'Comprehensive description of business model, operations, products/services, customers, and market opportunity',
      required: true,
      typicalWordCount: 6000,
      minWordCount: 4500,
      maxWordCount: 10000,
      requiredSubsections: ['Overview', 'Products/Services', 'Customer Base', 'Sales & Marketing', 'Operations', 'Research & Development'],
      mustInclude: ['Business model', 'Revenue streams', 'Customer concentration', 'Competition', 'Supplier relationships'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'MARKET_RESEARCH', 'BOARD_MINUTES'],
      aiGenerationGuidance: 'Tell the company story. Be descriptive. Use concrete examples and metrics. Show market understanding.',
    },
    {
      sectionId: 'NASDAQ-S1-08',
      sectionNumber: '8',
      sectionName: 'Executive Officers and Directors',
      sectionDescription: 'Detailed biographies of executive officers, board directors, advisors, and audit committee members',
      required: true,
      typicalWordCount: 4000,
      minWordCount: 3000,
      maxWordCount: 6000,
      requiredSubsections: ['Executive Officers', 'Board of Directors', 'Audit Committee', 'Compensation Committee', 'Nominating Committee'],
      mustInclude: ['Name and title', 'Age', 'Experience', 'Key achievements', 'Board committee memberships', 'Related party transactions'],
      complianceCategory: 'governance',
      priority: 'critical',
      dataSourceTypes: ['D_O_QUESTIONNAIRES', 'BOARD_MINUTES', 'EXECUTIVE_BIOS'],
      aiGenerationGuidance: 'Convert D&O questionnaires into compelling narrative. Highlight expertise relevant to company strategy.',
    },
    {
      sectionId: 'NASDAQ-S1-09',
      sectionNumber: '9',
      sectionName: 'Executive Compensation',
      sectionDescription: 'Detailed disclosure of executive compensation, equity awards, incentive plans, and severance arrangements',
      required: true,
      typicalWordCount: 4500,
      minWordCount: 3500,
      maxWordCount: 7000,
      requiredSubsections: ['Compensation Philosophy', 'Base Salary', 'Bonus Compensation', 'Equity Compensation', 'Severance Arrangements', 'CD&A'],
      mustInclude: ['Named executive officers', 'Base salaries', 'Bonus structure', 'Stock options/RSUs', 'Change of control provisions'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['EXECUTIVE_AGREEMENTS', 'BOARD_MINUTES', 'EMPLOYEE_OPTIONS'],
      aiGenerationGuidance: 'Present compensation in clear tables and narrative. Explain rationale for compensation structure.',
    },
    {
      sectionId: 'NASDAQ-S1-10',
      sectionNumber: '10',
      sectionName: 'Financial Statements and Supplementary Data',
      sectionDescription: 'Complete audited financial statements (balance sheet, income statement, cash flow, notes) per GAAP',
      required: true,
      typicalWordCount: 12000,
      minWordCount: 10000,
      maxWordCount: 20000,
      requiredSubsections: ['Consolidated Balance Sheet', 'Consolidated Statements of Operations', 'Consolidated Statements of Cash Flow', 'Notes to Financial Statements'],
      mustInclude: ['Auditor opinion', 'All GAAP financial statements', 'Segment information', 'Commitments and contingencies'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
      aiGenerationGuidance: 'Pull directly from audited financials. Do not modify or restate.',
    },
    {
      sectionId: 'NASDAQ-S1-11',
      sectionNumber: '11',
      sectionName: 'Certain Transactions and Relationships',
      sectionDescription: 'Disclosure of related party transactions, material contracts, and extraordinary transactions',
      required: true,
      typicalWordCount: 2500,
      minWordCount: 1500,
      maxWordCount: 4000,
      requiredSubsections: ['Related Party Transactions', 'Material Contracts', 'Indebtedness', 'Other Arrangements'],
      mustInclude: ['Transactions with directors/officers', 'Affiliate transactions', 'Loans from shareholders', 'Material service agreements'],
      complianceCategory: 'disclosure',
      priority: 'high',
      dataSourceTypes: ['MATERIAL_CONTRACTS', 'LEGAL_OPINIONS', 'BOARD_MINUTES'],
      aiGenerationGuidance: 'Full disclosure of any non-arm\'s-length transactions. Explain commercial rationale.',
    },
    {
      sectionId: 'NASDAQ-S1-12',
      sectionNumber: '12',
      sectionName: 'Legal Proceedings',
      sectionDescription: 'Disclosure of litigation, regulatory proceedings, and material legal disputes',
      required: true,
      typicalWordCount: 1500,
      minWordCount: 500,
      maxWordCount: 3000,
      requiredSubsections: ['Current Litigation', 'Regulatory Proceedings', 'Settled Matters'],
      mustInclude: ['Nature of proceedings', 'Parties involved', 'Relief sought', 'Current status', 'Estimated liability'],
      complianceCategory: 'legal',
      priority: 'high',
      dataSourceTypes: ['LEGAL_OPINIONS', 'INSURANCE_CERTIFICATES'],
      aiGenerationGuidance: 'Provide factual, objective summary. Include all material matters.',
    },
  ],
};

// ============================================================
// NYSE Form 10 Template (US IPO - Larger/Established Companies)
// ============================================================
export const NYSE_FORM10: ProspectusTemplate = {
  exchangeId: 'NYSE',
  version: '1.0',
  exchangeName: 'New York Stock Exchange',
  formType: 'Form 10',
  totalSections: 14,
  typicalTotalWordCount: 55000,
  complianceFramework: 'SEC Regulation S-K',
  estimatedCompletionDays: 55,
  requiresProfessionalReview: true,
  requiresAuditorSignoff: true,
  requiresLawyerSignoff: true,
  sections: [
    {
      sectionId: 'NYSE-10-01',
      sectionNumber: '1',
      sectionName: 'Business',
      sectionDescription: 'Comprehensive business description including organization, operations, products, customers, and competition',
      required: true,
      typicalWordCount: 7000,
      requiredSubsections: ['Overview', 'Market Segments', 'Products/Services', 'Customers', 'Competition', 'Regulatory Environment'],
      mustInclude: ['Organization structure', 'Product lines', 'Market share', 'Competitive positioning', 'Regulatory compliance'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'MARKET_RESEARCH', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'NYSE-10-02',
      sectionNumber: '1A',
      sectionName: 'Risk Factors',
      sectionDescription: 'Comprehensive risk disclosure',
      required: true,
      typicalWordCount: 6000,
      requiredSubsections: ['Business Risks', 'Financial Risks', 'Regulatory Risks', 'Market Risks', 'Cybersecurity Risks'],
      mustInclude: ['Material adverse changes', 'Industry-specific risks', 'Competitive threats', 'Regulatory/compliance risks'],
      complianceCategory: 'risk',
      priority: 'critical',
      dataSourceTypes: ['LEGAL_OPINIONS', 'MARKET_RESEARCH'],
    },
    {
      sectionId: 'NYSE-10-03',
      sectionNumber: '1B',
      sectionName: 'Unresolved Staff Comments',
      sectionDescription: 'Any unresolved comments from SEC staff',
      required: false,
      typicalWordCount: 0,
      requiredSubsections: [],
      mustInclude: [],
      complianceCategory: 'legal',
      priority: 'low',
      dataSourceTypes: [],
    },
    {
      sectionId: 'NYSE-10-04',
      sectionNumber: '2',
      sectionName: 'Properties',
      sectionDescription: 'Description of material properties owned or leased',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Owned Properties', 'Leased Properties', 'Facilities'],
      mustInclude: ['Location', 'Square footage', 'Use', 'Condition', 'Lease terms (if applicable)'],
      complianceCategory: 'disclosure',
      priority: 'medium',
      dataSourceTypes: ['PROPERTY_DOCUMENTS', 'BUSINESS_PLAN'],
    },
    {
      sectionId: 'NYSE-10-05',
      sectionNumber: '3',
      sectionName: 'Legal Proceedings',
      sectionDescription: 'Litigation and legal proceedings',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Current Litigation', 'Regulatory Actions', 'Settled Matters'],
      mustInclude: ['Nature of proceedings', 'Status', 'Potential liability', 'Insurance coverage'],
      complianceCategory: 'legal',
      priority: 'high',
      dataSourceTypes: ['LEGAL_OPINIONS', 'INSURANCE_CERTIFICATES'],
    },
    {
      sectionId: 'NYSE-10-06',
      sectionNumber: '4',
      sectionName: 'Mine Safety Disclosures',
      sectionDescription: 'MSHA safety data (if applicable to mining companies)',
      required: false,
      typicalWordCount: 0,
      requiredSubsections: [],
      mustInclude: [],
      complianceCategory: 'disclosure',
      priority: 'low',
      dataSourceTypes: [],
    },
    {
      sectionId: 'NYSE-10-07',
      sectionNumber: '5',
      sectionName: 'Market for Registrant\'s Common Equity',
      sectionDescription: 'Trading history, price ranges, dividend information',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Stock Exchange Listing', 'Trading Price', 'Dividend Policy'],
      mustInclude: ['Trading volume', 'Price ranges', 'Dividend history'],
      complianceCategory: 'disclosure',
      priority: 'medium',
      dataSourceTypes: ['BOARD_MINUTES'],
    },
    {
      sectionId: 'NYSE-10-08',
      sectionNumber: '6',
      sectionName: 'Selected Financial Data',
      sectionDescription: 'Five-year selected financial data',
      required: true,
      typicalWordCount: 3000,
      requiredSubsections: ['Five-Year Summary', 'Key Metrics', 'Per Share Data'],
      mustInclude: ['Revenue', 'Operating income', 'Net income', 'Total assets', 'Per share data'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
    },
    {
      sectionId: 'NYSE-10-09',
      sectionNumber: '7',
      sectionName: 'Management\'s Discussion and Analysis of Financial Condition and Results of Operations',
      sectionDescription: 'Detailed MD&A',
      required: true,
      typicalWordCount: 10000,
      requiredSubsections: ['Results of Operations', 'Liquidity and Capital Resources', 'Off-Balance Sheet Arrangements', 'Critical Accounting Estimates'],
      mustInclude: ['Year-over-year comparisons', 'Trend analysis', 'Cash flow analysis', 'Future outlook'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'BUSINESS_PLAN'],
    },
    {
      sectionId: 'NYSE-10-10',
      sectionNumber: '8',
      sectionName: 'Financial Statements and Supplementary Data',
      sectionDescription: 'Complete audited financial statements',
      required: true,
      typicalWordCount: 15000,
      requiredSubsections: ['Balance Sheet', 'Income Statement', 'Cash Flow Statement', 'Notes to Statements'],
      mustInclude: ['Auditor opinion', 'All required GAAP statements', 'Management certifications'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
    },
    {
      sectionId: 'NYSE-10-11',
      sectionNumber: '9',
      sectionName: 'Changes in and Disagreements with Accountants',
      sectionDescription: 'Any changes to auditors or disagreements',
      required: false,
      typicalWordCount: 500,
      requiredSubsections: [],
      mustInclude: [],
      complianceCategory: 'disclosure',
      priority: 'low',
      dataSourceTypes: [],
    },
    {
      sectionId: 'NYSE-10-12',
      sectionNumber: '9A',
      sectionName: 'Controls and Procedures',
      sectionDescription: 'Disclosure of internal controls and SOX compliance',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Disclosure Controls', 'Management\'s Assessment', 'Auditor Attestation'],
      mustInclude: ['CEO/CFO certifications', 'Control deficiencies', 'Remediation plans'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['BOARD_MINUTES'],
    },
    {
      sectionId: 'NYSE-10-13',
      sectionNumber: '10',
      sectionName: 'Executive Officers and Directors',
      sectionDescription: 'Detailed biographies and committee assignments',
      required: true,
      typicalWordCount: 5000,
      requiredSubsections: ['Executive Officers', 'Board of Directors', 'Audit Committee', 'Compensation Committee'],
      mustInclude: ['Experience', 'Expertise', 'Age', 'Board memberships', 'Committee roles'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['D_O_QUESTIONNAIRES', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'NYSE-10-14',
      sectionNumber: '11',
      sectionName: 'Executive Compensation',
      sectionDescription: 'Detailed compensation disclosure',
      required: true,
      typicalWordCount: 6000,
      requiredSubsections: ['Compensation Philosophy', 'Named Executive Officers', 'Equity Compensation', 'Severance'],
      mustInclude: ['Base salary', 'Bonus', 'Stock awards', 'Change of control provisions'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['EXECUTIVE_AGREEMENTS', 'BOARD_MINUTES'],
    },
  ],
};

// ============================================================
// TSX 2A / TSXV 2A Template (Canadian IPO)
// ============================================================
export const TSX_2A: ProspectusTemplate = {
  exchangeId: 'TSX',
  version: '1.0',
  exchangeName: 'Toronto Stock Exchange',
  formType: '2A',
  totalSections: 13,
  typicalTotalWordCount: 40000,
  complianceFramework: 'OSC/Canadian Securities Regulation',
  estimatedCompletionDays: 40,
  requiresProfessionalReview: true,
  requiresAuditorSignoff: true,
  requiresLawyerSignoff: true,
  sections: [
    {
      sectionId: 'TSX-2A-01',
      sectionNumber: '1',
      sectionName: 'Executive Summary',
      sectionDescription: 'Brief overview of business and offering highlights',
      required: true,
      typicalWordCount: 2500,
      requiredSubsections: ['Business Overview', 'Offering Terms', 'Use of Proceeds'],
      mustInclude: ['Company description', 'IPO price range', 'Share capital structure post-IPO'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'FINANCIAL_STATEMENTS'],
    },
    {
      sectionId: 'TSX-2A-02',
      sectionNumber: '2',
      sectionName: 'Corporate Structure',
      sectionDescription: 'Description of corporate organization and capitalization',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Formation', 'Capitalization', 'Shares Outstanding'],
      mustInclude: ['Articles of Incorporation', 'Share classes', 'Voting rights', 'Preferred share terms'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['ARTICLES_OF_INCORPORATION', 'CAP_TABLE'],
    },
    {
      sectionId: 'TSX-2A-03',
      sectionNumber: '3',
      sectionName: 'Business Description',
      sectionDescription: 'Overview of operations and market',
      required: true,
      typicalWordCount: 4000,
      requiredSubsections: ['Operations', 'Products/Services', 'Market', 'Competitive Environment'],
      mustInclude: ['Business model', 'Key customers', 'Competitive positioning', 'Market opportunity'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'MARKET_RESEARCH'],
    },
    {
      sectionId: 'TSX-2A-04',
      sectionNumber: '4',
      sectionName: 'Risk Factors',
      sectionDescription: 'Comprehensive risk disclosure',
      required: true,
      typicalWordCount: 3500,
      requiredSubsections: ['Business Risks', 'Market Risks', 'Regulatory Risks', 'Financial Risks'],
      mustInclude: ['Market risks', 'Competitive risks', 'Regulatory/legal risks', 'Liquidity risks'],
      complianceCategory: 'risk',
      priority: 'critical',
      dataSourceTypes: ['LEGAL_OPINIONS', 'MARKET_RESEARCH'],
    },
    {
      sectionId: 'TSX-2A-05',
      sectionNumber: '5',
      sectionName: 'Use of Proceeds',
      sectionDescription: 'Allocation of IPO proceeds',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Primary Use', 'Secondary Use', 'Timing'],
      mustInclude: ['Allocation percentages', 'Timeline', 'Contingencies'],
      complianceCategory: 'offering',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'FINANCIAL_STATEMENTS'],
    },
    {
      sectionId: 'TSX-2A-06',
      sectionNumber: '6',
      sectionName: 'Management and Board',
      sectionDescription: 'Executive and board information',
      required: true,
      typicalWordCount: 3000,
      requiredSubsections: ['Management Team', 'Board of Directors', 'Committee Structure'],
      mustInclude: ['Biographies', 'Expertise', 'Experience', 'Related party transactions'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['D_O_QUESTIONNAIRES', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'TSX-2A-07',
      sectionNumber: '7',
      sectionName: 'Compensation',
      sectionDescription: 'Executive compensation details',
      required: true,
      typicalWordCount: 2500,
      requiredSubsections: ['Named Executives', 'Compensation Structure', 'Equity Awards'],
      mustInclude: ['Base salary', 'Incentive compensation', 'Stock options/RSUs'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['EXECUTIVE_AGREEMENTS', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'TSX-2A-08',
      sectionNumber: '8',
      sectionName: 'Dividend Policy',
      sectionDescription: 'Dividend history and policy',
      required: false,
      typicalWordCount: 500,
      requiredSubsections: ['Historical Dividends', 'Future Policy'],
      mustInclude: [],
      complianceCategory: 'disclosure',
      priority: 'low',
      dataSourceTypes: ['BOARD_MINUTES'],
    },
    {
      sectionId: 'TSX-2A-09',
      sectionNumber: '9',
      sectionName: 'Financial Statements',
      sectionDescription: 'Audited financial statements per IFRS',
      required: true,
      typicalWordCount: 12000,
      requiredSubsections: ['Balance Sheet', 'Income Statement', 'Cash Flow', 'Notes'],
      mustInclude: ['Auditor opinion', 'IFRS compliance', 'Management certification'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
    },
    {
      sectionId: 'TSX-2A-10',
      sectionNumber: '10',
      sectionName: 'Management Discussion and Analysis',
      sectionDescription: 'Detailed MD&A of financial performance',
      required: true,
      typicalWordCount: 6000,
      requiredSubsections: ['Results of Operations', 'Liquidity and Capital Resources', 'Outlook'],
      mustInclude: ['YoY analysis', 'Key drivers', 'Future guidance'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'BUSINESS_PLAN'],
    },
    {
      sectionId: 'TSX-2A-11',
      sectionNumber: '11',
      sectionName: 'Material Contracts',
      sectionDescription: 'Summary of material contracts',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Key Contracts', 'Service Agreements', 'Supplier Agreements'],
      mustInclude: ['Customer concentration', 'Supplier dependencies', 'Termination rights'],
      complianceCategory: 'disclosure',
      priority: 'high',
      dataSourceTypes: ['MATERIAL_CONTRACTS'],
    },
    {
      sectionId: 'TSX-2A-12',
      sectionNumber: '12',
      sectionName: 'Related Party Transactions',
      sectionDescription: 'Disclosure of related party transactions',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Director/Officer Transactions', 'Affiliate Transactions', 'Loans'],
      mustInclude: ['Transaction nature', 'Terms', 'Related party relationship'],
      complianceCategory: 'disclosure',
      priority: 'high',
      dataSourceTypes: ['BOARD_MINUTES', 'LEGAL_OPINIONS'],
    },
    {
      sectionId: 'TSX-2A-13',
      sectionNumber: '13',
      sectionName: 'Legal Proceedings',
      sectionDescription: 'Litigation and legal proceedings',
      required: true,
      typicalWordCount: 1000,
      requiredSubsections: ['Current Proceedings', 'Settled Matters'],
      mustInclude: ['Nature', 'Status', 'Estimated exposure'],
      complianceCategory: 'legal',
      priority: 'high',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
  ],
};

// ============================================================
// CSE Form 2A Template (Canadian Venture)
// ============================================================
export const CSE_2A: ProspectusTemplate = {
  exchangeId: 'CSE',
  version: '1.0',
  exchangeName: 'Canadian Securities Exchange',
  formType: '2A',
  totalSections: 11,
  typicalTotalWordCount: 25000,
  complianceFramework: 'OSC Multi-Level Prospectus',
  estimatedCompletionDays: 30,
  requiresProfessionalReview: true,
  requiresAuditorSignoff: true,
  requiresLawyerSignoff: true,
  sections: [
    {
      sectionId: 'CSE-2A-01',
      sectionNumber: '1',
      sectionName: 'Executive Summary',
      sectionDescription: 'Brief overview',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Overview', 'Highlights'],
      mustInclude: ['Business summary', 'Key metrics'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN'],
    },
    {
      sectionId: 'CSE-2A-02',
      sectionNumber: '2',
      sectionName: 'Company Overview',
      sectionDescription: 'Organization and structure',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Formation', 'Structure', 'Capitalization'],
      mustInclude: ['Share structure', 'Voting rights'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['ARTICLES_OF_INCORPORATION', 'CAP_TABLE'],
    },
    {
      sectionId: 'CSE-2A-03',
      sectionNumber: '3',
      sectionName: 'Business and Operations',
      sectionDescription: 'Business description',
      required: true,
      typicalWordCount: 3000,
      requiredSubsections: ['Business Description', 'Market', 'Competition'],
      mustInclude: ['Products/services', 'Market opportunity', 'Competitive position'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'MARKET_RESEARCH'],
    },
    {
      sectionId: 'CSE-2A-04',
      sectionNumber: '4',
      sectionName: 'Risk Factors',
      sectionDescription: 'Risk disclosure',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Business Risks', 'Market Risks'],
      mustInclude: ['Key risks', 'Mitigation'],
      complianceCategory: 'risk',
      priority: 'critical',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
    {
      sectionId: 'CSE-2A-05',
      sectionNumber: '5',
      sectionName: 'Use of Proceeds',
      sectionDescription: 'Allocation of proceeds',
      required: true,
      typicalWordCount: 1000,
      requiredSubsections: ['Use of Funds'],
      mustInclude: ['Allocation', 'Timeline'],
      complianceCategory: 'offering',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN'],
    },
    {
      sectionId: 'CSE-2A-06',
      sectionNumber: '6',
      sectionName: 'Management and Governance',
      sectionDescription: 'Executive and board details',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Management', 'Board', 'Committees'],
      mustInclude: ['Biographies', 'Experience'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['D_O_QUESTIONNAIRES', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'CSE-2A-07',
      sectionNumber: '7',
      sectionName: 'Compensation',
      sectionDescription: 'Executive compensation',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Compensation'],
      mustInclude: ['Salary', 'Bonuses', 'Equity'],
      complianceCategory: 'governance',
      priority: 'medium',
      dataSourceTypes: ['EXECUTIVE_AGREEMENTS'],
    },
    {
      sectionId: 'CSE-2A-08',
      sectionNumber: '8',
      sectionName: 'Financial Statements',
      sectionDescription: 'Audited financials',
      required: true,
      typicalWordCount: 6000,
      requiredSubsections: ['Financial Statements'],
      mustInclude: ['Balance sheet', 'Income statement', 'Cash flow'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
    },
    {
      sectionId: 'CSE-2A-09',
      sectionNumber: '9',
      sectionName: 'MD&A',
      sectionDescription: 'Management discussion',
      required: true,
      typicalWordCount: 3000,
      requiredSubsections: ['Results of Operations', 'Liquidity'],
      mustInclude: ['YoY analysis', 'Key drivers'],
      complianceCategory: 'financial',
      priority: 'high',
      dataSourceTypes: ['FINANCIAL_STATEMENTS'],
    },
    {
      sectionId: 'CSE-2A-10',
      sectionNumber: '10',
      sectionName: 'Material Contracts',
      sectionDescription: 'Key contracts',
      required: true,
      typicalWordCount: 1000,
      requiredSubsections: ['Contracts'],
      mustInclude: ['Material agreements'],
      complianceCategory: 'disclosure',
      priority: 'medium',
      dataSourceTypes: ['MATERIAL_CONTRACTS'],
    },
    {
      sectionId: 'CSE-2A-11',
      sectionNumber: '11',
      sectionName: 'Legal Proceedings',
      sectionDescription: 'Litigation',
      required: true,
      typicalWordCount: 800,
      requiredSubsections: ['Proceedings'],
      mustInclude: ['Legal matters'],
      complianceCategory: 'legal',
      priority: 'medium',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
  ],
};

// ============================================================
// OTC Regulation A+ Template (US Reg A)
// ============================================================
export const OTC_REG_A: ProspectusTemplate = {
  exchangeId: 'OTC',
  version: '1.0',
  exchangeName: 'OTC Markets',
  formType: 'Regulation A+',
  totalSections: 10,
  typicalTotalWordCount: 20000,
  complianceFramework: 'SEC Regulation A',
  estimatedCompletionDays: 25,
  requiresProfessionalReview: true,
  requiresAuditorSignoff: false, // May not require full audit
  requiresLawyerSignoff: true,
  sections: [
    {
      sectionId: 'OTC-REGA-01',
      sectionNumber: '1',
      sectionName: 'Business Overview',
      sectionDescription: 'Business description and strategy',
      required: true,
      typicalWordCount: 2500,
      requiredSubsections: ['Business Model', 'Strategy', 'Key Metrics'],
      mustInclude: ['Company overview', 'Products/services', 'Market opportunity'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN'],
    },
    {
      sectionId: 'OTC-REGA-02',
      sectionNumber: '2',
      sectionName: 'Risk Factors',
      sectionDescription: 'Reg A+ risk disclosure',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Key Risks'],
      mustInclude: ['Material risks', 'Mitigation strategies'],
      complianceCategory: 'risk',
      priority: 'critical',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
    {
      sectionId: 'OTC-REGA-03',
      sectionNumber: '3',
      sectionName: 'Management and Officers',
      sectionDescription: 'Management team bios',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Management Team'],
      mustInclude: ['Experience', 'Expertise', 'Background'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['D_O_QUESTIONNAIRES'],
    },
    {
      sectionId: 'OTC-REGA-04',
      sectionNumber: '4',
      sectionName: 'Capitalization',
      sectionDescription: 'Share structure',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Capitalization Table'],
      mustInclude: ['Shares outstanding', 'Options/warrants'],
      complianceCategory: 'disclosure',
      priority: 'high',
      dataSourceTypes: ['CAP_TABLE'],
    },
    {
      sectionId: 'OTC-REGA-05',
      sectionNumber: '5',
      sectionName: 'Use of Proceeds',
      sectionDescription: 'How funds will be used',
      required: true,
      typicalWordCount: 1000,
      requiredSubsections: ['Fund Allocation'],
      mustInclude: ['Allocation breakdown', 'Timeline'],
      complianceCategory: 'offering',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN'],
    },
    {
      sectionId: 'OTC-REGA-06',
      sectionNumber: '6',
      sectionName: 'Financial Information',
      sectionDescription: 'Financial statements',
      required: true,
      typicalWordCount: 4000,
      requiredSubsections: ['Balance Sheet', 'Income Statement', 'MD&A'],
      mustInclude: ['Financial data', 'Key metrics'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS'],
    },
    {
      sectionId: 'OTC-REGA-07',
      sectionNumber: '7',
      sectionName: 'Compensation',
      sectionDescription: 'Executive compensation',
      required: true,
      typicalWordCount: 1000,
      requiredSubsections: ['Compensation Summary'],
      mustInclude: ['Salary', 'Equity'],
      complianceCategory: 'governance',
      priority: 'medium',
      dataSourceTypes: ['EXECUTIVE_AGREEMENTS'],
    },
    {
      sectionId: 'OTC-REGA-08',
      sectionNumber: '8',
      sectionName: 'Material Contracts',
      sectionDescription: 'Key business contracts',
      required: false,
      typicalWordCount: 800,
      requiredSubsections: ['Material Agreements'],
      mustInclude: [],
      complianceCategory: 'disclosure',
      priority: 'medium',
      dataSourceTypes: ['MATERIAL_CONTRACTS'],
    },
    {
      sectionId: 'OTC-REGA-09',
      sectionNumber: '9',
      sectionName: 'Dilution',
      sectionDescription: 'Share dilution analysis',
      required: true,
      typicalWordCount: 800,
      requiredSubsections: ['Dilution Analysis'],
      mustInclude: ['Pre and post IPO share counts', 'Dilution percentage'],
      complianceCategory: 'disclosure',
      priority: 'medium',
      dataSourceTypes: ['CAP_TABLE'],
    },
    {
      sectionId: 'OTC-REGA-10',
      sectionNumber: '10',
      sectionName: 'Legal Proceedings',
      sectionDescription: 'Litigation disclosure',
      required: true,
      typicalWordCount: 500,
      requiredSubsections: ['Legal Matters'],
      mustInclude: ['Pending litigation'],
      complianceCategory: 'legal',
      priority: 'medium',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
  ],
};

// ============================================================
// JSE (Japan) Template
// ============================================================
export const JSE_PROSPECTUS: ProspectusTemplate = {
  exchangeId: 'JSE',
  version: '1.0',
  exchangeName: 'Japan Exchange Group',
  formType: 'Listing Prospectus',
  totalSections: 12,
  typicalTotalWordCount: 35000,
  complianceFramework: 'Financial Instruments and Exchange Act (FIEA), JSDA Rules',
  estimatedCompletionDays: 50,
  requiresProfessionalReview: true,
  requiresAuditorSignoff: true,
  requiresLawyerSignoff: true,
  sections: [
    {
      sectionId: 'JSE-01',
      sectionNumber: '1',
      sectionName: 'Business Description',
      sectionDescription: 'Overview of business operations',
      required: true,
      typicalWordCount: 3500,
      requiredSubsections: ['Company Overview', 'Business Segments', 'Market Position'],
      mustInclude: ['Organizational structure', 'Business model', 'Market share', 'Competitive position'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['BUSINESS_PLAN', 'MARKET_RESEARCH'],
    },
    {
      sectionId: 'JSE-02',
      sectionNumber: '2',
      sectionName: 'Risk Factors',
      sectionDescription: 'Comprehensive risk disclosure per FIEA',
      required: true,
      typicalWordCount: 3000,
      requiredSubsections: ['Business Risks', 'Regulatory Risks', 'Market Risks'],
      mustInclude: ['Business continuity risks', 'Competitive risks', 'Regulatory changes'],
      complianceCategory: 'risk',
      priority: 'critical',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
    {
      sectionId: 'JSE-03',
      sectionNumber: '3',
      sectionName: 'Financial Condition',
      sectionDescription: 'Financial overview and highlights',
      required: true,
      typicalWordCount: 2500,
      requiredSubsections: ['Financial Summary', 'Key Metrics'],
      mustInclude: ['Revenue trends', 'Profitability', 'Capital structure'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS'],
    },
    {
      sectionId: 'JSE-04',
      sectionNumber: '4',
      sectionName: 'Management',
      sectionDescription: 'Management team and governance',
      required: true,
      typicalWordCount: 2000,
      requiredSubsections: ['Executive Officers', 'Board of Directors'],
      mustInclude: ['Management experience', 'Board expertise', 'Corporate governance'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['D_O_QUESTIONNAIRES', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'JSE-05',
      sectionNumber: '5',
      sectionName: 'Capitalization and Shares',
      sectionDescription: 'Share structure and capitalization',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Capital Structure', 'Share Details'],
      mustInclude: ['Shares outstanding', 'Voting rights', 'Share classes'],
      complianceCategory: 'disclosure',
      priority: 'critical',
      dataSourceTypes: ['CAP_TABLE', 'ARTICLES_OF_INCORPORATION'],
    },
    {
      sectionId: 'JSE-06',
      sectionNumber: '6',
      sectionName: 'Related Party Transactions',
      sectionDescription: 'Related party and affiliate transactions',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Related Parties', 'Transaction Details'],
      mustInclude: ['Director relationships', 'Affiliate transactions', 'Material contracts'],
      complianceCategory: 'disclosure',
      priority: 'high',
      dataSourceTypes: ['BOARD_MINUTES', 'LEGAL_OPINIONS'],
    },
    {
      sectionId: 'JSE-07',
      sectionNumber: '7',
      sectionName: 'Executive Compensation',
      sectionDescription: 'Compensation details per JSE requirements',
      required: true,
      typicalWordCount: 1500,
      requiredSubsections: ['Compensation Structure', 'Named Executives'],
      mustInclude: ['Salary ranges', 'Bonus details', 'Equity awards'],
      complianceCategory: 'governance',
      priority: 'high',
      dataSourceTypes: ['EXECUTIVE_AGREEMENTS', 'BOARD_MINUTES'],
    },
    {
      sectionId: 'JSE-08',
      sectionNumber: '8',
      sectionName: 'Financial Statements',
      sectionDescription: 'Audited financial statements per J-GAAP',
      required: true,
      typicalWordCount: 10000,
      requiredSubsections: ['Balance Sheet', 'Income Statement', 'Cash Flow', 'Notes'],
      mustInclude: ['Auditor opinion', 'J-GAAP compliance', 'English translation'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'AUDITOR_REPORTS'],
    },
    {
      sectionId: 'JSE-09',
      sectionNumber: '9',
      sectionName: 'MD&A',
      sectionDescription: 'Management discussion and analysis',
      required: true,
      typicalWordCount: 4000,
      requiredSubsections: ['Results Analysis', 'Liquidity Analysis', 'Future Outlook'],
      mustInclude: ['Performance drivers', 'Cash flow analysis', 'Strategic direction'],
      complianceCategory: 'financial',
      priority: 'critical',
      dataSourceTypes: ['FINANCIAL_STATEMENTS', 'BUSINESS_PLAN'],
    },
    {
      sectionId: 'JSE-10',
      sectionNumber: '10',
      sectionName: 'Use of Proceeds',
      sectionDescription: 'Allocation of IPO proceeds',
      required: true,
      typicalWordCount: 1000,
      requiredSubsections: ['Fund Allocation', 'Timeline'],
      mustInclude: ['Percentage allocation', 'Investment schedule', 'Contingency plans'],
      complianceCategory: 'offering',
      priority: 'high',
      dataSourceTypes: ['BUSINESS_PLAN'],
    },
    {
      sectionId: 'JSE-11',
      sectionNumber: '11',
      sectionName: 'Material Contracts and Arrangements',
      sectionDescription: 'Key agreements and arrangements',
      required: true,
      typicalWordCount: 1200,
      requiredSubsections: ['Contracts', 'Agreements'],
      mustInclude: ['Supplier agreements', 'Customer contracts', 'Distribution rights'],
      complianceCategory: 'disclosure',
      priority: 'high',
      dataSourceTypes: ['MATERIAL_CONTRACTS'],
    },
    {
      sectionId: 'JSE-12',
      sectionNumber: '12',
      sectionName: 'Legal Matters and Disputes',
      sectionDescription: 'Litigation and legal proceedings',
      required: true,
      typicalWordCount: 800,
      requiredSubsections: ['Pending Disputes', 'Regulatory Matters'],
      mustInclude: ['Material litigation', 'Regulatory investigations'],
      complianceCategory: 'legal',
      priority: 'high',
      dataSourceTypes: ['LEGAL_OPINIONS'],
    },
  ],
};

// ============================================================
// Master Template Registry
// ============================================================
export const PROSPECTUS_TEMPLATES: Record<string, ProspectusTemplate> = {
  'NASDAQ': NASDAQ_S1,
  'NYSE': NYSE_FORM10,
  'TSX': TSX_2A,
  'TSXV': TSX_2A, // TSXV uses same as TSX
  'CSE': CSE_2A,
  'OTC': OTC_REG_A,
  'JSE': JSE_PROSPECTUS,
};

/**
 * Get prospectus template for a specific exchange
 */
export function getProspectusTemplate(exchangeId: string): ProspectusTemplate | null {
  return PROSPECTUS_TEMPLATES[exchangeId] || null;
}

/**
 * Get all available exchanges
 */
export function getAvailableExchanges(): string[] {
  return Object.keys(PROSPECTUS_TEMPLATES);
}

/**
 * Get section by exchange and section ID
 */
export function getSection(exchangeId: string, sectionId: string): ProspectusSection | null {
  const template = getProspectusTemplate(exchangeId);
  if (!template) return null;
  return template.sections.find((s) => s.sectionId === sectionId) || null;
}
