-- Morning Briefing System Schema
-- Real-time news scraping, summarization, and impact assessment for IPO teams

-- News sources registry (20+ sources we monitor)
CREATE TABLE IF NOT EXISTS news_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE, -- "SEC EDGAR", "Crunchbase", "TechCrunch"
  url TEXT NOT NULL,
  category TEXT NOT NULL, -- "regulatory", "ipo", "competitor", "market"
  api_endpoint TEXT,
  api_key_vault_path TEXT, -- Reference to API key in secure vault
  scrape_frequency_minutes INT DEFAULT 60,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_category (category),
  INDEX idx_active (is_active)
);

-- Raw news articles (scraped from sources)
CREATE TABLE IF NOT EXISTS news_articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id UUID NOT NULL REFERENCES news_sources(id),
  headline TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  content TEXT,
  published_at TIMESTAMP,
  fetched_at TIMESTAMP DEFAULT NOW(),
  ai_summary TEXT, -- 2-3 sentence GPT-4 summary
  relevance_score FLOAT DEFAULT 0.5, -- 0-1 scale
  sentiment TEXT, -- "positive", "negative", "neutral"
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_source (source_id),
  INDEX idx_published (published_at),
  INDEX idx_relevance (relevance_score),
  INDEX idx_created (created_at)
);

-- Impact assessments per company (generated by AI)
CREATE TABLE IF NOT EXISTS news_impacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID NOT NULL REFERENCES news_articles(id) ON DELETE CASCADE,
  company_id UUID NOT NULL, -- Reference to company in main schema
  impact_type TEXT NOT NULL, -- "timeline_delay", "valuation_pressure", "opportunity", "regulatory", "competitive"
  impact_description TEXT,
  probability FLOAT NOT NULL, -- 0-1 confidence score
  expected_timeline_impact_days INT, -- How many days added/removed from IPO timeline
  recommended_action TEXT,
  urgency TEXT NOT NULL, -- "immediate", "this-week", "this-month"
  related_kpis TEXT[], -- KPI fields affected: ["cash_runway", "pace_score", etc.]
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_company (company_id),
  INDEX idx_article (article_id),
  INDEX idx_urgency (urgency),
  INDEX idx_created (created_at)
);

-- User news preferences and subscription settings
CREATE TABLE IF NOT EXISTS news_preferences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  company_id UUID NOT NULL,
  categories TEXT[] DEFAULT ARRAY['regulatory', 'competitor', 'market'], -- Which news types to receive
  email_enabled BOOLEAN DEFAULT true,
  email_time TIME DEFAULT '06:00', -- Local timezone
  email_frequency TEXT DEFAULT 'daily', -- "daily", "weekly", "immediate"
  in_app_enabled BOOLEAN DEFAULT true,
  competitors_to_track TEXT[] DEFAULT ARRAY[], -- Competitor company names
  exclude_categories TEXT[] DEFAULT ARRAY[], -- Categories to skip
  min_urgency_threshold TEXT DEFAULT 'this-month', -- Only show "immediate", "this-week", or "this-month"
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_user (user_id),
  INDEX idx_company (company_id),
  UNIQUE(user_id, company_id)
);

-- Daily briefing delivery tracking
CREATE TABLE IF NOT EXISTS briefing_sends (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  recipient_email TEXT NOT NULL,
  recipient_user_id UUID,
  articles_count INT NOT NULL,
  critical_alerts_count INT NOT NULL,
  sent_at TIMESTAMP DEFAULT NOW(),
  opened_at TIMESTAMP,
  clicked_at TIMESTAMP,
  actions_created_from_briefing INT DEFAULT 0,
  email_subject TEXT,
  email_preview TEXT, -- First 100 chars of content
  status TEXT DEFAULT 'sent', -- "draft", "sent", "bounced", "unsubscribed"
  INDEX idx_company (company_id),
  INDEX idx_sent (sent_at),
  INDEX idx_opened (opened_at)
);

-- Competitor tracking database
CREATE TABLE IF NOT EXISTS competitor_intelligence (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  competitor_name TEXT NOT NULL,
  competitor_identifier TEXT, -- Crunchbase ID, ticker, etc.
  latest_funding_amount DECIMAL,
  latest_funding_date TIMESTAMP,
  latest_valuation DECIMAL,
  growth_rate_pct FLOAT,
  revenue_estimate DECIMAL,
  gross_margin_pct FLOAT,
  last_updated TIMESTAMP DEFAULT NOW(),
  notes TEXT,
  INDEX idx_company (company_id),
  INDEX idx_competitor (competitor_name),
  UNIQUE(company_id, competitor_name)
);

-- News article metrics for analytics
CREATE TABLE IF NOT EXISTS article_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID NOT NULL REFERENCES news_articles(id) ON DELETE CASCADE,
  users_who_opened INT DEFAULT 0,
  users_who_saved INT DEFAULT 0,
  users_who_acted INT DEFAULT 0,
  engagement_score FLOAT DEFAULT 0, -- 0-1 calculated from above
  created_action_items INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_article (article_id)
);

-- Scheduled jobs for morning briefing
CREATE TABLE IF NOT EXISTS scheduled_briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL,
  schedule_cron TEXT NOT NULL, -- "0 6 * * *" for 6 AM daily
  timezone TEXT DEFAULT 'America/Toronto',
  is_active BOOLEAN DEFAULT true,
  last_run_at TIMESTAMP,
  next_run_at TIMESTAMP,
  last_error TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_company (company_id),
  INDEX idx_active (is_active),
  INDEX idx_next_run (next_run_at)
);

-- Briefing content template (versioning)
CREATE TABLE IF NOT EXISTS briefing_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  version INT DEFAULT 1,
  html_template TEXT NOT NULL, -- Handlebars template
  text_template TEXT,
  subject_line TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(name, version)
);

-- Action items created from news briefings
CREATE TABLE IF NOT EXISTS briefing_action_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  company_id UUID NOT NULL,
  article_id UUID REFERENCES news_articles(id),
  briefing_send_id UUID REFERENCES briefing_sends(id),
  title TEXT NOT NULL,
  description TEXT,
  due_date DATE,
  priority TEXT DEFAULT 'medium', -- "high", "medium", "low"
  status TEXT DEFAULT 'open', -- "open", "in_progress", "completed"
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP,
  INDEX idx_user (user_id),
  INDEX idx_company (company_id),
  INDEX idx_status (status),
  INDEX idx_due (due_date)
);

-- KPI snapshot at time of briefing (for correlation)
CREATE TABLE IF NOT EXISTS briefing_kpi_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  briefing_send_id UUID NOT NULL REFERENCES briefing_sends(id) ON DELETE CASCADE,
  pace_score INT,
  revenue_monthly DECIMAL,
  arr DECIMAL,
  gross_margin_pct FLOAT,
  cash_runway_months FLOAT,
  customer_churn_pct FLOAT,
  cap_table_clarity_pct FLOAT,
  governance_score INT,
  snapshot_at TIMESTAMP DEFAULT NOW(),
  INDEX idx_briefing (briefing_send_id)
);

-- Trigger to update timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to tables with updated_at
CREATE TRIGGER update_news_sources_timestamp
  BEFORE UPDATE ON news_sources
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_news_preferences_timestamp
  BEFORE UPDATE ON news_preferences
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scheduled_briefings_timestamp
  BEFORE UPDATE ON scheduled_briefings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_briefing_templates_timestamp
  BEFORE UPDATE ON briefing_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Insert default news sources
INSERT INTO news_sources (name, url, category, scrape_frequency_minutes) VALUES
-- SEC/Regulatory
('SEC EDGAR', 'https://www.sec.gov/cgi-bin/browse-edgar', 'regulatory', 120),
('SEC Announcements', 'https://www.sec.gov/news/pressreleases', 'regulatory', 240),
('FINRA Alerts', 'https://www.finra.org/newsroom', 'regulatory', 240),

-- IPO Market
('Crunchbase Funding', 'https://crunchbase.com/funding-rounds', 'ipo', 180),
('PitchBook IPOs', 'https://pitchbook.com/news/ipo-calendar', 'ipo', 240),
('IPO Scoop', 'https://www.iposcoop.com/', 'ipo', 360),
('Renaissance Capital IPO ETF', 'https://www.renaissancecapital.com/IPOs/', 'ipo', 360),

-- Company & Competitor News
('TechCrunch', 'https://techcrunch.com/', 'market', 60),
('Business Wire Press Releases', 'https://www.businesswire.com/', 'market', 120),
('Cision News', 'https://www.cision.com/us/', 'market', 120),

-- Banking & Investment Industry
('Goldman Sachs News', 'https://www.goldmansachs.com/insights/', 'ipo', 240),
('Morgan Stanley Research', 'https://www.morganstanley.com/research', 'ipo', 240),
('JPMorgan Insights', 'https://www.jpmorgan.com/insights', 'ipo', 240),

-- Market Intelligence
('Bloomberg Terminal Feed', 'https://www.bloomberg.com/', 'market', 60),
('Reuters Business', 'https://www.reuters.com/business/', 'market', 120),
('Financial Times', 'https://www.ft.com/', 'market', 120),

-- Analyst Reports
('Gartner Research', 'https://www.gartner.com/research', 'market', 720),
('Forrester Research', 'https://www.forrester.com/', 'market', 720),
('Deloitte Insights', 'https://www2.deloitte.com/us/en/insights.html', 'market', 720)
ON CONFLICT DO NOTHING;
