import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'
type BodyInit = string | ReadableStream<Uint8Array> | ArrayBuffer | FormData | URLSearchParams

interface Service {
  id: string
  name: string
  priceExpected: number
  description: string
}

interface RequestBody {
  selectedServices: Service[]
  budgets: {
    low: number
    expected: number
    aggressive: number
  }
  timestamp: string
}

// Helper function to convert HTML to PDF (simple text-based PDF generation)
function generatePdfContent(data: RequestBody): Buffer {
  const { selectedServices, budgets, timestamp } = data
  const date = new Date(timestamp).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  // Create a simple PDF using PDFKit-like approach with Buffer
  const pdfLines: string[] = []

  // PDF Header
  pdfLines.push('%PDF-1.4')
  pdfLines.push('1 0 obj')
  pdfLines.push('<< /Type /Catalog /Pages 2 0 R >>')
  pdfLines.push('endobj')
  pdfLines.push('2 0 obj')
  pdfLines.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>')
  pdfLines.push('endobj')
  pdfLines.push('3 0 obj')
  pdfLines.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>')
  pdfLines.push('endobj')

  // PDF Fonts
  pdfLines.push('5 0 obj')
  pdfLines.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
  pdfLines.push('endobj')

  // PDF Content Stream
  const contentLines: string[] = []
  contentLines.push('BT')
  contentLines.push('/F1 24 Tf 50 750 Td')
  contentLines.push('(Post-IPO Capital Markets Budget Summary) Tj')
  contentLines.push('0 -40 Td')
  contentLines.push('/F1 12 Tf')
  contentLines.push(`(Generated: ${date}) Tj`)
  contentLines.push('0 -30 Td')
  contentLines.push('/F1 14 Tf')
  contentLines.push('(Budget Overview) Tj')
  contentLines.push('0 -20 Td')
  contentLines.push('/F1 11 Tf')
  contentLines.push(`(Low Estimate: $${budgets.low.toLocaleString()}) Tj`)
  contentLines.push('0 -15 Td')
  contentLines.push(`(Expected: $${budgets.expected.toLocaleString()}) Tj`)
  contentLines.push('0 -15 Td')
  contentLines.push(`(Aggressive: $${budgets.aggressive.toLocaleString()}) Tj`)
  contentLines.push('0 -30 Td')
  contentLines.push('/F1 14 Tf')
  contentLines.push('(Selected Services) Tj')
  contentLines.push('0 -20 Td')
  contentLines.push('/F1 11 Tf')

  selectedServices.forEach((service) => {
    contentLines.push(`(• ${service.name}: $${service.priceExpected.toLocaleString()}/year) Tj`)
    contentLines.push('0 -15 Td')
  })

  contentLines.push('0 -20 Td')
  contentLines.push('/F1 14 Tf')
  contentLines.push('(Budget Metrics) Tj')
  contentLines.push('0 -20 Td')
  contentLines.push('/F1 11 Tf')
  contentLines.push(`(Total Expected Annual Budget: $${budgets.expected.toLocaleString()}) Tj`)
  contentLines.push('0 -15 Td')
  contentLines.push(`(Monthly Average: $${(budgets.expected / 12).toLocaleString('en-US', { maximumFractionDigits: 0 })}) Tj`)
  contentLines.push('0 -15 Td')
  contentLines.push(`(Number of Services: ${selectedServices.length}) Tj`)
  contentLines.push('0 -30 Td')
  contentLines.push('/F1 10 Tf')
  contentLines.push('(This budget summary was generated by the IPOReady Market IR Planner.) Tj')
  contentLines.push('0 -12 Td')
  contentLines.push('(Contact market@ipoready.com for vendor introductions) Tj')
  contentLines.push('ET')

  const content = contentLines.join('\n')

  pdfLines.push('4 0 obj')
  pdfLines.push(`<< /Length ${content.length} >>`)
  pdfLines.push('stream')
  pdfLines.push(content)
  pdfLines.push('endstream')
  pdfLines.push('endobj')

  // PDF Xref
  const xrefOffset = pdfLines.join('\n').length
  pdfLines.push('xref')
  pdfLines.push('0 6')
  pdfLines.push('0000000000 65535 f')
  pdfLines.push('0000000009 00000 n')
  pdfLines.push('0000000074 00000 n')
  pdfLines.push('0000000133 00000 n')
  pdfLines.push('0000000281 00000 n')
  pdfLines.push('0000000351 00000 n')

  // PDF Trailer
  pdfLines.push('trailer')
  pdfLines.push('<< /Size 6 /Root 1 0 R >>')
  pdfLines.push('startxref')
  pdfLines.push(xrefOffset.toString())
  pdfLines.push('%%EOF')

  return Buffer.from(pdfLines.join('\n'))
}

export async function POST(request: NextRequest) {
  try {
    const body: RequestBody = await request.json()

    if (!body.selectedServices || !body.budgets) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    const pdfBuffer = generatePdfContent(body)

    return new NextResponse(pdfBuffer as unknown as BodyInit, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="Market-IR-Budget-${Date.now()}.pdf"`,
      },
    })
  } catch (error) {
    console.error('PDF generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}
